### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by alexjfisher**
@earsdown Here are some commits to fix the rubocop violations that will occur after migrating to voxpupuli and doing a modulesync.

There were several hundred violations, so hopefully I've not messed anything up!

### CODE REVIEW

**Comment by alexjfisher** [comment]
https://github.com/earsdown/puppet-certmonger/pull/15/commits/932ac5b1fc738fb8b1350c227afe0006f95b2ea4 is probably the commit I'm most likely to have messed up.

**Comment by igalic** [comment]
this commit looks good to me, @alexjfisher

**Comment by JAORMX** [comment]
On a first glance it all looks good to me. I'll try it out in my deployment
on Monday.

**Comment by JAORMX** [comment]
Thanks a lot for this!

**Pull request merged**
